### ISSUE TITLE
route files with `-` in param name are not scanned

### ISSUE THREAD

**Issue by moshetanzer** [nitrojs/nitro#2868] opened 2024-11-11 07:24 UTC
### Environment

latest Nuxt 3.14.159 
node 23.1

### Reproduction

https://github.com/moshetanzer/nitro-server-route-bug

### Describe the bug

Hi,

Hope you are well.

I came across the above bug - not sure if it done like this on purpose.

A route with a dynamic param that contains a dash returns as 404 for example `[my-token].get.ts`
On Nuxt side (routing) it is normalized to `mytoken`

Couldn't find documented anywhere not to use kebab case.

Would maybe suggest normalizing it like Nuxt does (with frontend routing) - just to ensure consistency between the two.

@danielroe any thoughts?

Thanks so much for your work!

**Comment by pi0** [comment] 2024-11-11 12:11
I think for nitro api rotues, we should explicitly warn if params are not supported. [radix3](https://github.com/unjs/rou3/tree/radix3) and [rou3](https://github.com/unjs/rou3) for Nitro v3 have intentionally more restrictions to front-end routers like vue-router.

**Comment by pi0** [comment] 2024-11-11 12:29
Update: Seems a bug with scanner. runtime matcher supports `-` as param name.

You can use a custom config like this to allow param `test-param`:

```js
import { defineNitroConfig } from "nitropack/config";

export default defineNitroConfig({
  handlers: [
    {
      route: "/test/:test-param",
      handler: "routes/test/[test-param].ts",
    },
  ],

  compatibilityDate: "2024-11-11",
});
```

**Comment by moshetanzer** [comment] 2024-11-11 12:34
closed other warning pr then - is this the issue then `.replace(/\[(\w+)]/g, ":$1")` should it be replaced with this `.replace(/\[([\w-]+)]/g, ":$1")` to allow the dash?

**Comment by moshetanzer** [comment] 2024-11-11 12:35
would be happy to test - sorry to bug by asking. How can i get nitro working locally - for some reason when running pnpm install I get failed better-sqlite error?

**Comment by pi0** [comment] 2024-11-11 12:40
I made #2872 as fix in the meantime, and should be shortly fixed in [nightly](https://nitro.build/guide/nightly) channel.

---

I think you need to update your Node.js version (to 20 works for me) then use `pnpm build --stub` and then you can use `pnpm nitro dev playground` or `pnpm vitest test/presets/node.test.ts` to run tests against at least one preset. (if you had any other issues re setting up dev, please feel free to reach out 👍🏼 )

**Comment by pi0** [comment] 2024-11-11 12:44
Thanks for report and reproduction!

**Closed** 2024-11-11 12:44 UTC
Labels: bug
