### ISSUE TITLE
defineRouteMeta is not working with imported object

### ISSUE THREAD

**Issue by de-n3xus** [nitrojs/nitro#2870] opened 2024-11-11 11:48 UTC
### Environment

Node Version: v20.16.0
Nitro Version: v2.10.4

### Reproduction

https://stackblitz.com/edit/github-bwupnk?file=README.md

Route file:

```ts
defineRouteMeta({
	openAPI: {
		tags: ['/auth'],
		description: 'Authentication using login/email',
		requestBody: {
			required: true,
			content: {
				'application/json': {
					schema: {
						type: 'object',
						properties: {
							login: {
								type: 'string',
								description: 'Login/email of user',
							},
							password: {
								type: 'string',
								description: 'Password of user',
							},
						},
						required: ['login', 'password'],
					},
				},
			},
		},
		responses: {
			'200 (OK)': {
				description: 'Successful',
				content: {
					'application/json': {
						schema: {
							type: 'object',
							properties: {
								ok: {
									type: 'boolean',
									default: true,
								},
								result: {
									type: 'object',
									properties: {
										accessToken: {
											type: 'string',
											description: 'JWT Access token (1 day)',
										},
										refreshToken: {
											type: 'string',
											description: 'JWT Refresh token (14 days)',
										},
									},
								},
							},
						},
					},
				},
			},
			'4xx, 5xx': ErrorResponse,
		},
	},
})
```

ErrorResponse file:
```ts
import { ReferenceObject, ResponseObject } from 'openapi-typescript'

const response: ResponseObject | ReferenceObject = {
	description: 'Error',
	content: {
		'application/json': {
			schema: {
				type: 'object',
				properties: {
					ok: {
						type: 'boolean',
						default: false,
					},
					error: {
						type: 'object',
						properties: {
							message: {
								type: 'string',
								description: 'Message with error',
							},
						},
					},
				},
			},
		},
	},
}

export default response
```

### Describe the bug

4xx, 5xx response will not be shown in the openapi specification, but 200 will be

**Comment by danielroe** [comment] 2024-12-16 22:34
seems to be a duplicate of https://github.com/nitrojs/nitro/issues/2641

cc: @pi0

**Closed** 2024-12-16 22:35 UTC
Labels: pending triage
